### ISSUE TITLE
Multilanguage & localization

### ISSUE THREAD

**Issue by ponyatov** [bolerio/seco#49]
What approaches can I use for making SECO localization ?

- Interface
- manuals in GitHub markdown and Wiki

But maybe localization is drawback taking in mind low userbase and waste of efforts ?

**Comment by bolerio** [comment]
Hi,

It's never been a priority because there are enough important things to do beforehand, to my mind at least. But as a scripting shell, the software is functional enough that doing the effort might help, I dunno.  

For I18N (supporting other languages), there is a fairly standard way in Java using ResourceBundles, which is not complicated and can be done right now by simply externalizing all UI text into resource bundles. Because the long term vision is for this to be a distributed environment with HGDB underneath, I was always seeing the whole thing, including multiple languages, be bootstrapped from a P2P distributed DB so the UI would be fetched from "somewhere". So the alternative approach would be to host all resource in a DB and have Seco access them. We don't really have infrastructure for this, but it won't be "that hard" to set it up (a server with a HGDB instance that can be connected to during Seco niche creation) and it would be in the right direction.

With localization proper, I don't have that much experience and I'm not sure what's involved, besides time zone differences for example :)

But you are serious about it, about actually doing the work,please let me know, so we can go through some design conversation and I can help somehow.

**Comment by ponyatov** [comment]
I just translated README.md, and time waste too high comparing with user base.
I'll test i18n much much later when I will got working inference system and will fill knowledge base with materials.
